# DEVELOPMENT LAYER

FROM node:18-alpine As development

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node . .

USER node

# BUILD LAYER

FROM node:18-alpine As build

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules
COPY --chown=node:node index.js ./

COPY --chown=node:node . .

ENV NODE_ENV production

RUN npm ci --only=production && npm cache clean --force

USER node

# PRODUCTION LAYER

FROM node:18-alpine As production

LABEL maintainer="aivironcom@gmail.com" version="1.0"

COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node package*.json ./
COPY --chown=node:node index.js ./


EXPOSE 6000

ENV CART_SERVICE_KEY=cart PRODUCT_SERVICE_KEY=product CART_SERVICE_API="" PRODUCT_SERVICE_API=""

CMD [ "node", "index.js" ]
